export default [
	{
		id: '1',
		name: 'Model S',
		tagline: 'Order Online for',
		taglineCTA: 'Touchless Delivery',
		image: require('../../assets/images/ModelS.jpeg'),
		type: 'car',
	},
	{
		id: '2',
		name: 'Model 3',
		tagline: 'Order Online for',
		taglineCTA: 'Touchless Delivery',
		image: require('../../assets/images/Model3.jpeg'),
		type: 'car',
	},
	{
		id: '3',
		name: 'Model X',
		tagline: 'Order Online for',
		taglineCTA: 'Touchless Delivery',
		image: require('../../assets/images/ModelX.jpeg'),
		type: 'car',
	},
	{
		id: '4',
		name: 'Model Y',
		tagline: 'Order Online for',
		taglineCTA: 'Touchless Delivery',
		image: require('../../assets/images/ModelY.jpeg'),
		type: 'car',
	},
	{
		id: '5',
		name: 'Solar Roof',
		tagline: 'Produce Clean Energy From Your Roof',
		image: require('../../assets/images/SolarRoof.jpeg'),
		type: 'solar',
	},
	{
		id: '6',
		name: 'Solar Panels',
		tagline: 'Lowest Cost Solar Panels in America',
		image: require('../../assets/images/SolarPanels.jpeg'),
		type: 'solar',
	},
	{
		id: '7',
		name: 'Accessories',
		image: require('../../assets/images/accessories.jpeg'),
		type: 'accessories',
	},
]
